"""
    rotations = grid_rotations(maxradians, rgridsz, SD)

Generate a `Vector{AffineMap}` of candidate rotation transforms for use in a
coarse rotation grid search.

`maxradians` is either a single maximum angle (in 2D) or a tuple of maximum
Euler angles (in 3D and higher). `rgridsz` is one or more integers specifying
the number of grid points along each rotation axis; values should be odd so that
zero rotation is included. `SD` is a matrix specifying the sample spacing
(see [`arrayscale`](@ref)).

# Examples

```jldoctest
julia> using LinearAlgebra

julia> rots = grid_rotations(π/8, 3, Matrix{Float64}(I, 2, 2));

julia> length(rots)
3

julia> rots3d = grid_rotations((π/8, π/8, π/8), (3,3,3), Matrix{Float64}(I, 3, 3));

julia> length(rots3d)
27
```
"""
function grid_rotations(maxradians, rgridsz, SD)
    rgridsz = [rgridsz...]
    maxradians = [maxradians...]
    nd = size(SD, 1)
    if !all(isodd, rgridsz)
        @warn("rgridsz should be odd; rounding up to the next odd integer")
    end
    for i in 1:length(rgridsz)
        if !isodd(rgridsz[i])
            rgridsz[i] = max(round(Int, rgridsz[i]) + 1, 1)
        end
    end
    grid_radius = map(x -> div(x, 2), rgridsz)
    if nd > 2
        gridcoords = [range(-grid_radius[x] * maxradians[x], stop = grid_radius[x] * maxradians[x], length = rgridsz[x]) for x in 1:nd]
        rotation_angles = Iterators.product(gridcoords...)
    else
        rotation_angles = range(-grid_radius[1] * maxradians[1], stop = grid_radius[1] * maxradians[1], length = rgridsz[1])
    end
    axmat = Matrix{Float64}(I, nd, nd)
    axs = map(x -> axmat[:, x], 1:nd)
    tfeye = tformeye(nd)
    output = typeof(tfeye)[]
    for ra in rotation_angles
        if nd > 2
            euler_rots = map(x -> tformrotate(x...), zip(axs, ra))
            rot = foldr(∘, euler_rots, init = tfeye)
        elseif nd == 2
            rot = tformrotate(ra)
        else
            error("Unsupported dimensionality")
        end
        push!(output, AffineMap(SD * rot.linear / SD, zeros(nd))) #account for sample spacing
    end
    return output
end

"""
    best_tform, best_mm = rotation_gridsearch(fixed, moving, maxshift, maxradians, rgridsz;
                                              SD=Matrix{Float64}(I,ndims(fixed),ndims(fixed)))

Search a grid of rotations to coarsely align `moving` to `fixed`.

Returns `(best_tform, best_mm)` where `best_tform` is an `AffineMap` encoding the
best-found rotation and translation, and `best_mm` is the corresponding mismatch
value (lower is better).

For each candidate rotation (generated by [`grid_rotations`](@ref)), the best
integer-pixel translation of up to `maxshift` pixels is found via a Fourier method.
The candidate with the lowest combined mismatch is returned.

See [`grid_rotations`](@ref) for how `maxradians`, `rgridsz`, and `SD` shape the search.

!!! note
    A mismatch backend such as
    [RegisterMismatch.jl](https://github.com/HolyLab/RegisterMismatch.jl) must be
    loaded before calling this function.

# Examples

```jldoctest
julia> using RegisterMismatch, CoordinateTransformations, Rotations, ImageFiltering, ImageTransformations

julia> fixed = Float64.(reshape(1:100, 10, 10));

julia> moving = warp(centered(fixed), LinearMap(RotMatrix(π/16)));

julia> best_tform, best_mm = rotation_gridsearch(
           collect(centered(fixed)), collect(float(moving)), (3,3), π/8, 3);

julia> best_mm < 0.1
true
```
"""
function rotation_gridsearch(fixed, moving, maxshift, maxradians, rgridsz; SD = Matrix{Float64}(I, ndims(fixed), ndims(fixed)))
    rgridsz = [rgridsz...]
    nd = ndims(moving)
    @assert nd == ndims(fixed)
    rots = grid_rotations(maxradians, rgridsz, SD)
    best_mm = Inf
    best_rot = tformeye(nd)
    best_shift = zeros(nd)
    for rot in rots
        new_moving = transform(moving, rot)
        #calc mismatch
        #mm = mismatch(fixed, new_moving, maxshift; normalization=:pixels)
        mm = mismatch(fixed, new_moving, maxshift)
        thresh = 0.1 * maximum(x -> x.denom, mm)
        best_i = argmin_mismatch(mm, thresh)
        cur_best = ratio(mm[best_i], 0.0)
        if cur_best < best_mm
            best_mm = cur_best
            best_rot = rot
            best_shift = [best_i.I...]
        end
    end
    return tformtranslate(best_shift) ∘ best_rot, best_mm
end
